### ISSUE TITLE
Use blockbridge-docker-volume encounter an error

### ISSUE THREAD

**Issue by coolljt0725** [blockbridge/blockbridge-docker-volume#1]
Hi, 
  I try the blockbridge-docker-volume and encounter an error. 

<pre><code>docker run --rm -ti --volume busybox-demo:/data --volume-driver=blockbridge busybox sh
Error response from daemon: Plugin Error: {"Err":"volume-busybox-demo bb_provision failed: ERROR: bb api lookup disk info -d volume-busybox-demo -X label failed: Blockbridge::Api::UnauthorizedError Unauthorized"}</code></pre>

docker logs 

<pre><code>docker logs bbsim-mn
-- running in container
Setting default management configuration...
'/bb/etc/sim-mncfg.lua' -> '/bb/etc/mncfg.lua'
Generating node TLS key and self-signed certificate: done.
Starting Blockbridge simulator node:1
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.42.3. Set the 'ServerName' directive globally to suppress this message
Waiting for management node to boot...
== Updated user: system (USR1B69A94C40626440)
== Created account: block (ACT0769794C40626470)

== Account: block (ACT0769794C40626470)
name                  block                    
label                 block                    
serial                ACT0769794C40626470      
created               2015-08-17 11:44:57 +0000
disabled              no                       

==============================================
Blockbridge simulator (container) has started.

Mode:            management
Management node: management-57f449d1ae9f
IP Address:      10.175.105.123
Admin API Key:   1/AKZm/SJiIkGXsadez4u1NivlQvtNzXxY9O34LQtL6EAQpmb9ImIjAA
Admin account:   system
Admin password:  9b40dfa0720a8cd181e58812c073ec2d
User account:    block
User password:   c492822f41abcdd4df91586435731d2f

==============================================</code></pre>

**Comment by srust** [comment]
Hi,

Thanks for filing an issue. It looks like your simulator is up and running!

Each Blockbridge volume is provisioned for a specific USER in the system. In order to do this, two separate pieces of configuration must be in place.

First, the Blockbridge volume driver must be configured with an Admin API key. This is shown in the output of the Blockbridge simulator as:

```
Admin API Key:   1/AKZm/SJiIkGXsadez4u1NivlQvtNzXxY9O34LQtL6EAQpmb9ImIjAA
```

Make sure this is set in the blockbridge volume driver correctly. You can inspect the driver to see the environment configuration:

```
docker inspect --format='{{.Config.Env}}' blockbridge-volume-driver
```

Second, configure the volume. You are using a volume called `busybox-demo`. Each volume configuration lives in `/bb/env` by default. Can you please show what is in the file `/bb/env/busybox-demo`? This configuration lets you set the user, capacity of the volume, other volume parameters.

A USER is required in this file, such as:

```
$ cat /bb/env/busybox-demo
TYPE=autovol
USER=block
CAPACITY=32GiB
```

The USER line tells Blockbridge what user to provision the volume for. It is recommended to use a non-system account for the volumes. They can be separate users for each volume, although not required.

Please make sure the USER line is set correctly for your volume.

Thanks! Let us know.

**Comment by srust** [comment]
As a followup, I have updated the README to use the `block` user in the example. In the current version of the code, the USER specified in the env file must exist on the backend in order to be used for a volume. If the user does not exist, an authentication error will occur.

Either configure the volume to use an existing user (as now shown in the example), or create the user in the backend first.

**Comment by coolljt0725** [comment]
@srust  I set the `USER` in the `/bb/env/busybox-demo` and it works. Thanks for your help
